[package]
name = "treadcam"
version = "0.1.0"
authors = ["Michael Sloan <mgsloan@gmail.com>"]

[dependencies]
rscam = "0.5.4"
image = "0.17.0"
serde = "1.0.66"
serde_json = "1.0.20"
serde_derive = "1.0.66"
rustfft = "2.0.0"
goertzel = "0.2.0"
